apiVersion: apps/v1
kind: Deployment
metadata:
  name: xaiqo-chatbot
  labels:
    app: xaiqo-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xaiqo-chatbot
  template:
    metadata:
      labels:
        app: xaiqo-chatbot
    spec:
      containers:
      - name: xaiqo-chatbot
        image: xaiqo-chatbot:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2"
        env:
        - name: USE_GPU
          value: "false"
        - name: MODEL_PATH
          value: "/app/models/final_model"
        - name: MAX_SEQ_LENGTH
          value: "512"
        volumeMounts:
        - name: model-storage
          mountPath: /app/models
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: xaiqo-model-storage